### ISSUE TITLE
Overcome altair data transformer in Heroku 

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/spotify-explorer-py#10]
Altair required data transformer when number of rows are more than 5000 which our dataset has .
Altair data transformer is not supported in Heroku, we need to find a work around.

**Comment by michelle-wms** [comment]
I've overcome that by adding a line of code in my IA1

# Handle large data sets by not embedding them in the notebook
alt.data_transformers.enable('data_server')

**Comment by christopheralex** [comment]
Found this on github https://github.com/altair-viz/altair_data_server/issues/11

I get a blank plot without any data points when I tried `alt.data_transformers.enable('data_server')`

**Comment by michelle-wms** [comment]
I tried deploying with alt.data_transformers.disable_max_rows() and it works! :D
