### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/spotify-explorer-py#18]

**Comment by xiangwxt** [comment]
Hi team, I have a general suggestion on the plot layout and style. I feel like the first 3 plots are not lined up very well, and they are all in one color. Maybe we'd like to format them a little bit as a whole? Maybe make them all have the same tick count, same height for the two at the bottom, and maybe make the fist one a little bit wider? What do you think? @jennifer-hoang @michelle-wms @christopheralex
