### ISSUE TITLE
Dashboard functionality discussion

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/spotify-explorer-py#3]
Discuss on the 4 plots which the dashboard is going to contain.

**Comment by christopheralex** [comment]
Please go through the dataset and comment on the functionalities ideas.

**Comment by jennifer-hoang** [comment]
Functionality Ideas

- Distribution of track_popularity by playlist_genres / subgenres (violin plot?)
  - To determine which genres/genre combinations have the most popular songs
- Ranking of track_popularity by track_artist, or track_album (bar chart, top 10)
  - To show most popular artists and albums at the time of data collection

**Comment by michelle-wms** [comment]
- Trendline: After selecting the genre OR artist you want to zoom in (upon looking at the top popular ones from jenn's violin plot/barchart), displays the trend of the past few years of this genre/artist.

**Comment by christopheralex** [comment]
Was thinking on the lines of - 
A graph which is interacted by the user providing a popularity score and the output is the artist name and their corresponding number of songs ( only artists who have songs greater than the provided popularity score )
Just a general idea for now which can be refined later .
I think it relates to @jennifer-hoang idea .

**Comment by xiangwxt** [comment]
- I'm thinking having a line chart or histogram showing the popularity of songs against the properties of the songs to show how popularity rank distributed over different properties of songs. The user can select the property they want to check in a dropdown menu. This chart kind of links the numeric columns in the data.
- Or I'm thinking we could show the decay of popularity of album against their release date to help user see how long they could stay popular.

**Comment by jennifer-hoang** [comment]
Chosen plots based on group discussion:
- Ranking of top artists (filter by genre) - Jenn
- Popularity Trend of Specific Artists (filter by artists) - Michelle
- Popularity Distribution of Specific Artists (filter by artists) - Chris
- Popular Song Characteristics (dropdown of song characteristics) - Wenxin
