### ISSUE TITLE
Add appropriate docstring for plotting functions

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/spotify-explorer-py#33]
- [x] Remove layout initial docstring added by Chris in components.py (Chris)
- [x] Add function docstring to all plotting functions in Numpy style. ( Michelle, Jenn , Thea )
- [x] Could add one line docstring for layout functions. (Chris and whoever wants to help :P )

**Comment by xiangwxt** [comment]
I have updated mine: plot-4.
